### ISSUE TITLE
Does not work in Laravel 9

### ISSUE THREAD

**Issue by farhadhp** [bangnokia/laravel-backup-telegram#1]
Hi,
I have installed this package. However, when I execute the command "backup:run", the backup file is not sent to Telegram. The size of the backup file is 5 MB and the output of the "backup:run" command is as follows.

```
Starting backup...
Dumping database prj_1...
Determining files to backup...
Zipping 6317 files and directories...
Created zip containing 6317 files and directories. Size is 5.1 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Sending notification failed
Backup completed!
```

**Comment by bangnokia** [comment]
hi @farhadhp , the default notification with `spatie/laravel-backup` is the `email` channel. If you don't configure email credentials, it will fail when sending notifications and didn't fire back up events. So you can ignore this by publishing the `backup.php` config file:
```bash
php artisan vendor:publish --provider="Spatie\Backup\BackupServiceProvider"
```

and change the setting `backup.mail.to` to an empty string.
```php
 'mail' => [
            'to' => '',

            'from' => [
                'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),
                'name' => env('MAIL_FROM_NAME', 'Example'),
            ],
        ],
```

**Comment by farhadhp** [comment]
Thankyou 🙏🏻
